### PR TITLE
refactor setup fn content to be slightly more optimized and clean.

### PR DESCRIPTION
**Pull request by jaymanmdev**
Hi, I just watched your video showcasing this library - I do think it is a great idea. I don't think I'm going to actually use it though, not that there are any issues with it. It looks genuinely nice and lightweight for small projects, but as I am a big fan of HTMX and what it offers, I'm definitely going to stick to it.
Theoretically it might be nice to add some Go tests in here to test that everything still works, but I am confident that these changes are simple and straightforward enough that things aren't broken lol.
I just made some optimizations to the setup loops. You are looping THREE separate times unnecessarily when you can just do a single forEach to speed up computation greatly, and the time complexity will be much better for larger DOM trees. :) This is a very subjective and opinionated implementation, but I'm putting it out there if you wish to merge it in.
Thanks!

### CODE REVIEW

**Comment by jaymanmdev** [comment]
And I renamed the example directory as it isn't using Go Fiber, it's using Echo haha :D

**Comment by awesome-club** [comment]
Thank you for your feedback and contribution!

You are right - that implementation was not efficient at all (Bad JS programming habits I guess) so I'll follow your lead on this one.

`const [prefixChar, ...evtName] = evt.name;` - I thing this one assigns the `['l', 'o', 'a', 'd']` array to `evtName` am I right?
This means that `evtName === "load"` will always be false. 
Am I missing something? Maybe you had something else in mind?

**Comment by jaymanmdev** [comment]
Yep! That is a great call out - I forgot how the spread destructuring worked - it'll turn it into an array, not a string haha - that's my bad!
Check out my edits - I used a simple .at call to index the first character, and then I slice the rest of the attribute name. I merged the two forEach loops as well as it's unnecessary to loop over every attribute twice for each element, and I merged them into a couple if check branches.
I think this'll work well :)

**Comment by jaymanmdev** [comment]
I'm off to bed now, but I just realised there are some micro-optimisations that could still be made.

This is more for cleaner code, but we could pull up some of the nested if statements inside of the '=== "@"' block. E.g. 'if (prefixChar.at(0) === "@" && evtName === "load")'

We could pull out the callback function within the '=== ":"' block as that function is going to be created in memory on every attribute that matches it. This will likely perform "eh" with larger DOM trees. It'll stress out JavaScript's GC lol
Why not pass in the name and whatever is needed as parameters? And only create the function on the top level. It probably isn't a huge deal but it is a possibility?

**Comment by awesome-club** [comment]
@jaymanmdev Thank you - good stuff!

Yep, you are right about the GC optimisation as well - will explore that further!

Thanks again for your time and suggestions! Keep them coming!

**Pull request merged**
